Importing the Libraries

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf

Part 1 - Data Preprocessing

Importing the Dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


Encoding the Categorical Data

Label Encoding the 'Gender' Column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

Label Encoding the 'Geography' Column

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

Splitting the Dataset into the Training Set and Testing Set

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

Feature Scaling

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Part 2 - Building the ANN

Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the Output layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Part 3 - Training the ANN

Compiling the ANN

In [14]:
# for categoricial loss = categorical_crossentropy & activation = softmax
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

Training the ANN on the Training Set

In [15]:
ann.fit(X_train,y_train,batch_size=601,epochs=100)

Epoch 1/100


14/14 [==============================] - 1s 2ms/step - loss: 0.6379 - accuracy: 0.7234
Epoch 2/100
14/14 [==============================] - 0s 2ms/step - loss: 0.6167 - accuracy: 0.7694
Epoch 3/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5995 - accuracy: 0.7897
Epoch 4/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5854 - accuracy: 0.7955
Epoch 5/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5726 - accuracy: 0.7960
Epoch 6/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5615 - accuracy: 0.7960
Epoch 7/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5508 - accuracy: 0.7960
Epoch 8/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5414 - accuracy: 0.7960
Epoch 9/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5325 - accuracy: 0.7960
Epoch 10/100
14/14 [==============================] - 0s 2ms/step - loss: 0.5243 - accuracy: 0.7960
Epoch 11/100
14/14 [=

In [16]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 6)                 78        
                                                                 
 dense_1 (Dense)             (None, 6)                 42        
                                                                 
 dense_2 (Dense)             (None, 1)                 7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


Part 4 - Making the Predictions and Evaluating the Model

Predicting the result of a single observation

In [17]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5)

1/1 [==============================] - 0s 117ms/step
[[False]]


Predicting the Test Set Results

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

 1/63 [..............................] - ETA: 1s

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1537   58]
 [ 247  158]]


0.8475